export default {
	Debug: 0,
	RSA: 1,
	AES: 2,
	Meta: 3,
	MetaResponse: 4,
	Register: 5,
	MemberLogin: 6,
	GuestLogin: 7,
	LoginResponse: 8,
	Input: 9,
	Message: 10,
	LoginFinished: 11,
	ChannelListUpdate: 12,
	GroupListUpdate: 13,
	UserListUpdate: 14,
	EnterChannel: 15,
	EnterChannelResponse: 16,
	GetSettings: 17,
	GetSettingsResponse: 18,
	OpenSettings: 19,
	OpenSettingsResponse: 20,
	EditSettings: 21,
	EditSettingsResponse: 22
}